version: 2

job_common: &job_common
  docker:
    - image: circleci/node:10.21-stretch
  working_directory: ~/argent-contracts
job_python: &job_python
  docker:
    - image: circleci/python:3.8.0b1-stretch-node
  working_directory: ~/argent-contracts
step_save_cache: &step_save_cache
  save_cache:
    paths:
      - ~/.cache/package-lock
    key: node-modules-{{ checksum "package-lock.json" }}
step_restore_cache: &step_restore_cache
  restore_cache:
    keys:
      - node-modules-{{ checksum "package-lock.json" }}
step_setup_global_packages: &step_setup_global_packages
  run:
    name: "Set up global packages"
    command: |
      npm install
step_setup_slither: &step_setup_slither
  run:
    name: "Setup slither analyser https://github.com/crytic/slither"
    command: |
      sudo pip3 install slither-analyzer
      sudo apt-get install jq
step_setup_solc_select: &step_setup_solc_select
  run:
    name: "Setup solc-select"
    command: |
      git clone https://github.com/crytic/solc-select.git
      bash ./solc-select/scripts/install.sh
jobs:
  unit-test:
    <<: *job_common
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - run:
          name: "Lint Solidity contracts"
          command: npm run lint:contracts
      - run:
          name: "Testing deployment scripts and benchmark gas costs"
          command: npm run ganache >/dev/null 2>&1 & npm run test:deployment && npm run test:benchmark
      - run:
          name: "Compiling external library contracts"
          command: npm run compile:lib
      - run:
          name: "Compiling legacy contracts"
          command: npm run compile:legacy
      - run:
          name: "Compiling contracts"
          command: npm run compile
      - run:
          name: "Compiling test contracts"
          command: npm run compile:test
      - run:
          name: "Lint JavaScript"
          command: npm run lint:js
      - run:
          name: "Running unit tests"
          command: npm run ganache >/dev/null 2>&1 & npm run test
      - run:
          name: "Running coverage"
          command: |
            npm run compile
            npm run compile:test
            npm run test:coverage
      - <<: *step_save_cache
      # Save coverage artifacts
      - store_artifacts:
          path: coverage
  security-test:
    <<: *job_python
    steps:
      - checkout
      - <<: *step_restore_cache
      - <<: *step_setup_global_packages
      - <<: *step_setup_slither
      - <<: *step_setup_solc_select
      - run:
          name: "Validate TokenPriceRegistry tokens against ERC20 standard"
          command: |
            export PATH=/home/circleci/.solc-select:$PATH
            echo "export PATH=/home/circleci/.solc-select:$PATH" >> ~/.bashrc
            solc --version
      - run:
          name: "Check TokenPriceRegistry tokens for ERC20 compliance"
          command: npm run validate:erc20
      - run:
          name: "Run slither"
          command: npm run security:slither
workflows:
  version: 2
  commit:
    jobs:
      - unit-test
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *" # 1am UTC
          filters:
            branches:
              only:
                - develop
    jobs:
      - security-test
